[package]
name = "prusti-viper"
version = "0.1.0"
authors = ["Prusti Devs <prusti_developers@sympa.ethz.ch>"]
edition = "2021"

[lib]
doctest = false # we have no doc tests

[dependencies]
rustc-hash = "1.1.0"
viper = { path = "../viper" }
vir = { path = "../vir" }
