name: Build GitHub pages

on:
  workflow_dispatch:
  push:
    branches: 'master'
    paths: 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: "repo"

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Prepare output directory
        run: |
          mkdir -p output

      - name: Build user guide
        run: |
          cd repo/docs/user-guide
          mdbook build -d ../../../output/user-guide

      - name: Build dev guide
        run: |
          cd repo/docs/dev-guide
          mdbook build -d ../../../output/dev-guide

      - name: Copy static content
        run: |
          cp -r repo/docs/static/* output

      - name: Publish to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          keep_files: true
