name: Test on crates

on:
  workflow_dispatch:
  push:
    branches: [master, staging, trying]
    paths-ignore: 'docs/**'

jobs:
  # Test `cargo-prusti` on a collection of crates.
  test-crates:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: true
